=== SimeonHristov99/courier-services/courier_services.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT orders (order*)>
        <!ELEMENT order (id, from, to, details)>

        <!ELEMENT id (#PCDATA)>
        <!ELEMENT from (note?, company)>
        <!ELEMENT note (#PCDATA)>
        <!ELEMENT company (name?, address, employee)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT address (district?, city, parking?)>
        <!ELEMENT district (#PCDATA)>
        <!ELEMENT city (zip_code, name?, neighbourhood?, street?)>
        <!ELEMENT zip_code (#PCDATA)>
        <!ELEMENT neighbourhood (#PCDATA)>
        <!ELEMENT street (name, number)>
        <!ELEMENT number (#PCDATA)>
        <!ELEMENT parking EMPTY>
        <!ELEMENT employee (emp_name?, phones, emails?)>
        <!ELEMENT emp_name (first?, last)>
        <!ELEMENT first (#PCDATA)>
        <!ELEMENT last (#PCDATA)>
        <!ELEMENT phones (phone)+>
        <!ELEMENT phone (code, number)>
        <!ELEMENT code (#PCDATA)>
        <!ELEMENT emails (email)+>
        <!ELEMENT email (#PCDATA)>

        <!ELEMENT to (note?, company)>

        <!ELEMENT details (pickoff, dropoff, price, verification?, freight)>
        <!ELEMENT pickoff (date, time?)>
        <!ELEMENT date EMPTY>
        <!ELEMENT time EMPTY>
        <!ELEMENT dropoff (date, time?)>
        <!ELEMENT price (value, currency)>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT currency (#PCDATA)>
        <!ELEMENT verification (signature)?>
        <!ELEMENT signature (#PCDATA)>
        <!ELEMENT freight (dimensions, quantity, weight, requires_van, call_customer, food)>
        <!ELEMENT dimensions (width, height)>
        <!ELEMENT width (#PCDATA)>
        <!ELEMENT height (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT requires_van EMPTY>
        <!ELEMENT call_customer EMPTY>
        <!ELEMENT food EMPTY>

        <!ATTLIST phone notification (Да|Не) "Не">
        <!ATTLIST email notification (Да|Не) "Да">
        <!ATTLIST parking available (Да|Не) #REQUIRED>
        <!ATTLIST dimensions units CDATA #REQUIRED>
        <!ATTLIST weight units CDATA #REQUIRED>
        <!ATTLIST requires_van value (Да|Не) #REQUIRED>
        <!ATTLIST call_customer value (Да|Не) #REQUIRED>
        <!ATTLIST food value (Да|Не) #REQUIRED>
        <!ATTLIST price level (Веднага|2часа|4часа|12часа) #REQUIRED>
        <!ATTLIST company code CDATA #REQUIRED>
        <!ATTLIST date year CDATA #REQUIRED>
        <!ATTLIST date month CDATA #REQUIRED>
        <!ATTLIST date day CDATA #REQUIRED>
        <!ATTLIST time hours CDATA #REQUIRED>
        <!ATTLIST time minutes CDATA #REQUIRED>

=== SimeonHristov99/courier-services/valid_xml_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE orders SYSTEM "courier_services.dtd">

<orders>
    <order>
        <id>3</id>
        <from>
            <company code="131448974">
                <name>Си 3 ай Европа</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1766</zip_code>
                        <name>София</name>
                        <neighbourhood>Младост 4</neighbourhood>
                        <street>
                            <name>Бизнес парк София</name>
                            <number>1</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Рахул</first>
                        <last>Сингх</last>
                    </emp_name>
                    <phones>
                        <phone notification="Да">
                            <code>359</code>
                            <number>248 982 78</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>rsingh@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </from>
        <to>
            <company code="131448974">
                <name>Си 3 ай Европа</name>
                <address>
                    <district>Варна</district>
                    <city>
                        <zip_code>9002</zip_code>
                        <name>Варна</name>
                        <neighbourhood>Център</neighbourhood>
                        <street>
                            <name>Сливница</name>
                            <number>24</number>
                        </street>
                    </city>
                    <parking available="Не"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Шив</first>
                        <last>Валиа</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>257 522 46</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>shvalia@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </to>
        <details>
            <pickoff>
                <date year="2020" month="04" day="22"/>
                <time hours="08" minutes="00"/>
            </pickoff>
            <dropoff>
                <date year="2020" month="04" day="22"/>
                <time hours="13" minutes="15"/>
            </dropoff>
            <price level="Веднага">
                <value>1500</value>
                <currency>евро</currency>
            </price>
            <verification>
                <signature>eN67VS_l69GHpPCW1uPzfQ</signature>
            </verification>
            <freight>
                <dimensions units="м">
                    <width>20</width>
                    <height>1</height>
                </dimensions>
                <quantity>15</quantity>
                <weight units="кг">750</weight>
                <requires_van value="Да"/>
                <call_customer value="Да"/>
                <food value="Не"/>
            </freight>
        </details>
    </order>
</orders>

=== SimeonHristov99/courier-services/valid_xml_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE orders SYSTEM "courier_services.dtd">

<orders>
    <order>
        <id>2</id>
        <from>
            <note>Влиза се през ул. Николай Ракитин 2. Моля служителят се качи на етаж 6</note>
            <company code="204473764">
                <name>Старс Интерактив Сървиз (България)</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1124</zip_code>
                        <name>София</name>
                        <neighbourhood>Яворов</neighbourhood>
                        <street>
                            <name>Цариградско шосе</name>
                            <number>47а</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Адам</first>
                        <last>Коуел</last>
                    </emp_name>
                    <phones>
                        <phone notification="Да">
                            <code>359</code>
                            <number>249 515 80</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>akcauel@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </from>
        <to>
            <company code="204605415">
                <name>Капабо</name>
                <address>
                    <district>Русе</district>
                    <city>
                        <zip_code>7000</zip_code>
                        <name>Русе</name>
                        <neighbourhood>Хъшове</neighbourhood>
                        <street>
                            <name>Александровска</name>
                            <number>26</number>
                        </street>
                    </city>
                    <parking available="Не"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Александър</first>
                        <last>Ангелов</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>889 503 073</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>aangelov@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </to>
        <details>
            <pickoff>
                <date year="2019" month="05" day="19"/>
                <time hours="09" minutes="00"/>
            </pickoff>
            <dropoff>
                <date year="test" month="05" day="19"/>
                <time hours="17" minutes="20"/>
            </dropoff>
            <price level="12часа">
                <value>550</value>
                <currency>лева</currency>
            </price>
            <verification>
                <signature>0ZGKSfjGPBkEY8_qmxtE9g</signature>
            </verification>
            <freight>
                <dimensions units="м">
                    <width>10</width>
                    <height>10</height>
                </dimensions>
                <quantity>1</quantity>
                <weight units="кг">250</weight>
                <requires_van value="Да"/>
                <call_customer value="Да"/>
                <food value="Не"/>
            </freight>
        </details>
    </order>
</orders>

=== SimeonHristov99/courier-services/valid_xml_5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE orders SYSTEM "courier_services.dtd">

<orders>
    <order>
        <id>5</id>
        <from>
            <company code="115829812">
                <name>ИЗИ КОНСУЛТ</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1766</zip_code>
                        <name>София</name>
                        <neighbourhood>Младост 4</neighbourhood>
                        <street>
                            <name>д-р Атанас Москов</name>
                            <number>15</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Христо</first>
                        <last>Палазов</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>248 958 85</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>hpalazov@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </from>
        <to>
            <company code="201803961">
                <name>СТАНГА</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1407</zip_code>
                        <name>София</name>
                        <neighbourhood>Лозенец</neighbourhood>
                        <street>
                            <name>Черни връх</name>
                            <number>43</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Мариана</first>
                        <last>Методиева</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>32550071</number>
                        </phone>
                        <phone>
                            <code>359</code>
                            <number>526 031 90</number>
                        </phone>
                        <phone>
                            <code>359</code>
                            <number>819 604 121</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>mmetodieva@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </to>
        <details>
            <pickoff>
                <date year="2020" month="11" day="29"/>
                <time hours="12" minutes="40"/>
            </pickoff>
            <dropoff>
                <date year="2020" month="11" day="30"/>
                <time hours="00" minutes="05"/>
            </dropoff>
            <price level="12часа">
                <value>54.99</value>
                <currency>лева</currency>
            </price>
            <verification>
                <signature>6PMunN53KIenRyKTVBWYeg</signature>
            </verification>
            <freight>
                <dimensions units="см">
                    <width>600</width>
                    <height>600</height>
                </dimensions>
                <quantity>150</quantity>
                <weight units="кг">50</weight>
                <requires_van value="Да"/>
                <call_customer value="Да"/>
                <food value="Да"/>
            </freight>
        </details>
    </order>
</orders>

=== SimeonHristov99/courier-services/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE orders SYSTEM "courier_services.dtd">

<orders>
    <order>
        <id>4</id>
        <from>
            <company code="831919536">
                <name>УниКредит Булбанк</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1000</zip_code>
                        <name>София</name>
                        <neighbourhood>Център</neighbourhood>
                        <street>
                            <name>Света Неделя</name>
                            <number>7</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Георги</first>
                        <last>Кирилов</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>851 423 694</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>gkirilov@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </from>
        <to>
            <company code="115840214">
                <name>Профилинк</name>
                <address>
                    <district>Пловдив</district>
                    <city>
                        <zip_code>4023</zip_code>
                        <name>Пловдив</name>
                        <neighbourhood>Южна промишлена зона</neighbourhood>
                        <street>
                            <name>Нестор Абаджиев</name>
                            <number>55</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Йордан</first>
                        <last>Фиданов</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>887 088 851</number>
                        </phone>
                    </phones>
                    <emails>
                        <email notification="Не">ifidanov@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </to>
        <details>
            <pickoff>
                <date year="2020" month="12" day="02"/>
                <time hours="11" minutes="00"/>
            </pickoff>
            <dropoff>
                <date year="2020" month="12" day="02"/>
                <time hours="13" minutes="00"/>
            </dropoff>
            <price level="2часа">
                <value>150</value>
                <currency>долара</currency>
            </price>
            <verification>
                <signature>ytEsaZisQneClzWje4aY0Q</signature>
            </verification>
            <freight>
                <dimensions units="см">
                    <width>200</width>
                    <height>100</height>
                </dimensions>
                <quantity>50</quantity>
                <weight units="кг">15</weight>
                <requires_van value="Не"/>
                <call_customer value="Да"/>
                <food value="Да"/>
            </freight>
        </details>
    </order>
</orders>

=== SimeonHristov99/courier-services/valid_xml_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE orders SYSTEM "courier_services.dtd">

<orders>
    <order>
        <id>1</id>
        <from>
            <company code="204952162">
                <name>ФМИ</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1766</zip_code>
                        <name>София</name>
                        <neighbourhood>Младост</neighbourhood>
                        <street>
                            <name>Витошки камбани</name>
                            <number>9</number>
                        </street>
                    </city>
                    <parking available="Не"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Павел</first>
                        <last>Павлов</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>885 865 066</number>
                        </phone>
                    </phones>
                    <emails>
                        <email notification="Да">pmanev@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </from>
        <to>
            <note>На този адрес има още две фирми. Астреа Рикрутмънт се намира в офис 3</note>
            <company code="203088121">
                <name>Астреа Рикрутмънт</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1309</zip_code>
                        <name>София</name>
                        <neighbourhood>Възраждане</neighbourhood>
                        <street>
                            <name>Царибродска</name>
                            <number>70</number>
                        </street>
                    </city>
                    <parking available="Да"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Мая</first>
                        <last>Иванова</last>
                    </emp_name>
                    <phones>
                        <phone notification="Да">
                            <code>359</code>
                            <number>882 467 851</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>mivanova@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </to>
        <details>
            <pickoff>
                <date year="test" month="01" day="11"/>
                <time hours="11" minutes="11"/>
            </pickoff>
            <dropoff>
                <date year="2020" month="01" day="11"/>
                <time hours="14" minutes="55"/>
            </dropoff>
            <price level="2часа">
                <value>50</value>
                <currency>лева</currency>
            </price>
            <verification>
                <signature>lqIMx78wHyf1PndUdsrKBQ</signature>
            </verification>
            <freight>
                <dimensions units="см">
                    <width>250</width>
                    <height>165</height>
                </dimensions>
                <quantity>5</quantity>
                <weight units="кг">2.5</weight>
                <requires_van value="Не"/>
                <call_customer value="Да"/>
                <food value="Не"/>
            </freight>
        </details>
    </order>

    <order>
        <id>6</id>
        <from>
            <note>Служителят да се качи на етаж 4.</note>
            <company code="175108293">
                <name>ПРОКСИАД БЪЛГАРИЯ ЕАД</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1113</zip_code>
                        <name>София</name>
                        <neighbourhood>Дианабад</neighbourhood>
                        <street>
                            <name>Тинтява</name>
                            <number>13б</number>
                        </street>
                    </city>
                    <parking available="Не"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Стефан</first>
                        <last>Леви</last>
                    </emp_name>
                    <phones>
                        <phone notification="Да">
                            <code>359</code>
                            <number>2 980 91 03</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>slevi@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </from>
        <to>
            <company code="202506991">
                <name>Понтика Солюшънс ООД</name>
                <address>
                    <district>София</district>
                    <city>
                        <zip_code>1505</zip_code>
                        <name>София</name>
                        <neighbourhood>Оборище</neighbourhood>
                        <street>
                            <name>Черковна</name>
                            <number>38</number>
                        </street>
                    </city>
                    <parking available="Не"/>
                </address>
                <employee>
                    <emp_name>
                        <first>Иван</first>
                        <last>Георгиев</last>
                    </emp_name>
                    <phones>
                        <phone>
                            <code>359</code>
                            <number>24912488</number>
                        </phone>
                    </phones>
                    <emails>
                        <email>igeorgiev@gmail.com</email>
                    </emails>
                </employee>
            </company>
        </to>
        <details>
            <pickoff>
                <date year="2020" month="12" day="30"/>
                <time hours="19" minutes="00"/>
            </pickoff>
            <dropoff>
                <date year="2020" month="12" day="31"/>
                <time hours="17" minutes="20"/>
            </dropoff>
            <price level="12часа">
                <value>50</value>
                <currency>лева</currency>
            </price>
            <verification>
                <signature>TXsuj8yqfynPDunkRnG7bw</signature>
            </verification>
            <freight>
                <dimensions units="м">
                    <width>20</width>
                    <height>15</height>
                </dimensions>
                <quantity>5</quantity>
                <weight units="кг">45</weight>
                <requires_van value="Да"/>
                <call_customer value="Да"/>
                <food value="Не"/>
            </freight>
        </details>
    </order>

</orders>
